apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-project
  labels:
    product: insurence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance
      tier: web
  template:
    metadata:
      labels:
        app: insurance
        tier: web
    spec:
      containers:
      - name: insurence
        image: anjalisingh99/insurance:latest
        ports:
        - containerPort: 8080
        resources:
          limits:  
            cpu: 1000m
