apiVersion: v1
kind: Service
metadata:
  name: insurance-project
  labels:
    app: insurance
spec:
  ports:
   - name: insurence
     port: 8081
     targetPort: 8081
  type: NodePort
  selector:
    app: insurance
    tier: web

